### ISSUE TITLE
can not run successfully build_kbs.py

### ISSUE THREAD

**Issue by Fil-onto** [sg-wbi/belb#2]
When executing python -m belb.scripts.build_kbs --dir /dir --db  db.yaml --cores 20, I get the following error.

```2024-10-21 15:00:36.697 | INFO     | belb.kbs.kb:to_belb:211 - Start converting ctd_diseases to BELB format...
100%|██████████| 1.78M/1.78M [00:01<00:00, 1.59MiB/s]
2024-10-21 15:00:38.359 | INFO     | belb.kbs.kb:write_table:144 - Start writing `kb` table file...
2024-10-21 15:00:38.695 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 10000 entries...
2024-10-21 15:00:39.066 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 20000 entries...
2024-10-21 15:00:39.422 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 30000 entries...
2024-10-21 15:00:39.776 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 40000 entries...
2024-10-21 15:00:40.125 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 50000 entries...
2024-10-21 15:00:40.482 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 60000 entries...
2024-10-21 15:00:40.840 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 70000 entries...
2024-10-21 15:00:41.201 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 80000 entries...
2024-10-21 15:00:41.563 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 90000 entries...
2024-10-21 15:00:41.589 | INFO     | belb.kbs.kb:write_table:183 - Complted writing `kb` table: 90730 total entries.
2024-10-21 15:00:41.590 | INFO     | belb.kbs.kb:write_table:144 - Start writing `identifier_mapping` table file...
2024-10-21 15:00:41.761 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 10000 entries...
2024-10-21 15:00:41.973 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 20000 entries...
2024-10-21 15:00:42.024 | INFO     | belb.kbs.kb:write_table:183 - Complted writing `identifier_mapping` table: 21294 total entries.
2024-10-21 15:00:42.025 | INFO     | belb.kbs.kb:__init__:300 - Database was not initialized. Call `init_database` before anything else...
2024-10-21 15:00:42.044 | INFO     | belb.kbs.kb:init_database:371 - Initilializing knowledge base database...
2024-10-21 15:00:43.767 | INFO     | belb.kbs.kb:to_database:360 - Completed populating table `kb`
2024-10-21 15:00:44.016 | INFO     | belb.kbs.kb:to_database:360 - Completed populating table `identifier_mapping`
2024-10-21 15:00:44.026 | INFO     | belb.kbs.kb:to_belb:211 - Start converting ctd_chemicals to BELB format...
100%|██████████| 10.0M/10.0M [00:02<00:00, 4.09MiB/s]
2024-10-21 15:00:47.228 | INFO     | belb.kbs.kb:write_table:144 - Start writing `kb` table file...
2024-10-21 15:00:50.993 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 100000 entries...
2024-10-21 15:00:54.868 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 200000 entries...
2024-10-21 15:00:58.645 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 300000 entries...
2024-10-21 15:01:02.273 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 400000 entries...
2024-10-21 15:01:04.481 | INFO     | belb.kbs.kb:write_table:183 - Complted writing `kb` table: 461122 total entries.
2024-10-21 15:01:04.482 | INFO     | belb.kbs.kb:write_table:144 - Start writing `identifier_mapping` table file...
2024-10-21 15:01:06.642 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 100000 entries...
2024-10-21 15:01:08.505 | INFO     | belb.kbs.kb:write_table:183 - Complted writing `identifier_mapping` table: 179178 total entries.
2024-10-21 15:01:08.506 | INFO     | belb.kbs.kb:__init__:300 - Database was not initialized. Call `init_database` before anything else...
2024-10-21 15:01:08.508 | INFO     | belb.kbs.kb:init_database:371 - Initilializing knowledge base database...
2024-10-21 15:01:16.748 | INFO     | belb.kbs.kb:to_database:360 - Completed populating table `kb`
2024-10-21 15:01:18.677 | INFO     | belb.kbs.kb:to_database:360 - Completed populating table `identifier_mapping`
2024-10-21 15:01:18.704 | INFO     | belb.kbs.kb:to_belb:211 - Start converting ncbi_taxonomy to BELB format...
100%|██████████| 67.4M/67.4M [00:11<00:00, 6.09MiB/s]
2024-10-21 15:01:30.390 | INFO     | belb.kbs.kb:write_table:144 - Start writing `kb` table file...
2024-10-21 15:02:14.318 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 1000000 entries...
2024-10-21 15:02:47.479 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 2000000 entries...
2024-10-21 15:03:22.152 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 3000000 entries...
2024-10-21 15:03:55.152 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 4000000 entries...
2024-10-21 15:04:01.869 | INFO     | belb.kbs.kb:write_table:183 - Complted writing `kb` table: 4195999 total entries.
2024-10-21 15:04:01.869 | INFO     | belb.kbs.kb:write_table:144 - Start writing `history` table file...
2024-10-21 15:04:28.612 | INFO     | belb.kbs.kb:write_table:183 - Complted writing `history` table: 757726 total entries.
2024-10-21 15:04:28.613 | INFO     | belb.kbs.kb:__init__:300 - Database was not initialized. Call `init_database` before anything else...
2024-10-21 15:04:28.616 | INFO     | belb.kbs.kb:init_database:371 - Initilializing knowledge base database...
2024-10-21 15:05:58.101 | INFO     | belb.kbs.kb:to_database:360 - Completed populating table `kb`
2024-10-21 15:06:04.293 | INFO     | belb.kbs.kb:to_database:360 - Completed populating table `history`
2024-10-21 15:06:04.304 | INFO     | belb.kbs.kb:to_belb:211 - Start converting cellosaurus to BELB format...
100%|██████████| 112M/112M [00:21<00:00, 5.18MiB/s]
100%|██████████| 2.67k/2.67k [00:00<00:00, 1.28MiB/s]
2024-10-21 15:06:28.679 | INFO     | belb.kbs.kb:write_table:144 - Start writing `kb` table file...
2024-10-21 15:06:33.095 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 100000 entries...
2024-10-21 15:06:38.398 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 200000 entries...
2024-10-21 15:06:42.585 | INFO     | belb.kbs.kb:write_table:183 - Complted writing `kb` table: 281507 total entries.
2024-10-21 15:06:42.586 | INFO     | belb.kbs.kb:write_table:144 - Start writing `identifier_mapping` table file...
2024-10-21 15:06:44.435 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 100000 entries...
2024-10-21 15:06:45.839 | INFO     | belb.kbs.kb:write_table:183 - Complted writing `identifier_mapping` table: 160015 total entries.
2024-10-21 15:06:45.839 | INFO     | belb.kbs.kb:write_table:144 - Start writing `history` table file...
2024-10-21 15:06:45.840 | INFO     | belb.kbs.kb:write_table:183 - Complted writing `history` table: 37 total entries.
2024-10-21 15:06:45.841 | INFO     | belb.kbs.kb:write_table:144 - Start writing `citations` table file...
2024-10-21 15:06:47.058 | INFO     | belb.kbs.kb:write_table:176 - #PROGRESS: written 100000 entries...
2024-10-21 15:06:47.627 | INFO     | belb.kbs.kb:write_table:183 - Complted writing `citations` table: 143101 total entries.
2024-10-21 15:06:47.627 | INFO     | belb.kbs.kb:write_table:144 - Start writing `foreign_identifiers` table file...
2024-10-21 15:06:47.635 | INFO     | belb.kbs.kb:write_table:183 - Complted writing `foreign_identifiers` table: 878 total entries.
2024-10-21 15:06:47.636 | INFO     | belb.kbs.kb:__init__:300 - Database was not initialized. Call `init_database` before anything else...
2024-10-21 15:06:47.637 | INFO     | belb.kbs.kb:init_database:371 - Initilializing knowledge base database...
2024-10-21 15:06:53.121 | INFO     | belb.kbs.kb:to_database:360 - Completed populating table `kb`
2024-10-21 15:06:54.540 | INFO     | belb.kbs.kb:to_database:360 - Completed populating table `identifier_mapping`
2024-10-21 15:06:54.553 | INFO     | belb.kbs.kb:to_database:360 - Completed populating table `history`
2024-10-21 15:06:56.104 | INFO     | belb.kbs.kb:to_database:360 - Completed populating table `citations`
2024-10-21 15:06:56.122 | INFO     | belb.kbs.kb:to_database:360 - Completed populating table `foreign_identifiers`
2024-10-21 15:06:56.127 | INFO     | belb.kbs.kb:update_foreign_identifiers:607 - Updating `foreign_identifiers` table with names
Traceback (most recent call last):
  File "/home/filip/Downloads/belb-main/belb/scripts/build_kbs.py", line 113, in <module>
    main()
  File "/home/filip/Downloads/belb-main/belb/scripts/build_kbs.py", line 109, in main
    NAME_TO_KB_MODULE[kb.name].main(args)
  File "/home/filip/Downloads/belb-main/belb/kbs/cellosaurus/cellosaurus.py", line 269, in main
    handle.update_foreign_identifiers(foreign_kb=foreign_kb)
  File "/home/filip/Downloads/belb-main/belb/kbs/kb.py", line 637, in update_foreign_identifiers
    query = foreign_kb.queries.get(
  File "/home/filip/Downloads/belb-main/belb/kbs/query.py", line 79, in get
    raise ValueError(f"{self.__class__.__name__} has not method `{do}`!")
ValueError: BelbKbQuery has not method `get_identifier_preferred_name`!

Process finished with exit code 1```

**Comment by sg-wbi** [comment]
Thank you for trying out BELB and sorry for the late reply.

The problem is that I forgot to remove some code that was connected to a subsequent publication (see [here](https://academic.oup.com/bioinformatics/article/40/8/btae474/7721929) if you are interested).

Now it should work ([387111ff52b670350e0108ffaf8e25d995e28708](https://github.com/sg-wbi/belb/commit/387111ff52b670350e0108ffaf8e25d995e28708)).
